config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'admin', to: 'admin#index'

  controller :pages do
    get :qr_code_generator
    get :qr_code_download
  end

  resources :follows
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'about/index'
  get 'promo/index'
  resources :subscribers
  resources :posts do
    resources :comments
    resources :likes
    resources :favorites
  end

  resources :users
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  get 'users/:id/following', :to => "users#following", :as => :following

  get 'post/index'
  get 'welcome/index'
  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'

  resources :users, only: [:show, :edit, :update]


  get 'posts/:id', to: 'posts#show'

  get 'comments', to: 'comments#index'
  # get 'comments/:id', to: 'comments#show'


  root 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'promo#index'
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
		mount_uploader :image, ImageUploader
		has_many :comments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		belongs_to :user
		belongs_to :category

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :likes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_posts, :through => :favorites, :source => :post

    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
    has_many :followees, through: :followed_users
    has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
    has_many :followers, through: :following_users
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<% if user_signed_in? && current_user.isadmin == true%>

<div class="admin-page">
    <div class="admin-nav">
            <div class='admin-link' style='background: #C8DAE5; '>
                <div class='admin-logo' style='background-image: url(../../../assets/posts.png);'></div>
                <strong><%= link_to "Публикации", admin_path %></strong>
            </div>
            <div class='admin-link'>
                <div class='admin-logo' style='background-image: url(../../../assets/users.png);'></div>
                <%= link_to "Пользователи", users_path %>
            </div>
            <div class='admin-link'>
                <div class='admin-logo' style='background-image: url(../../../assets/genres.png);'></div>
                <%= link_to "Жанры", categories_path %>
            </div>
            <div class='admin-link' >
                <div class='admin-logo' style='background-image: url(../../../assets/collections.png);'></div>
                <a href="">Подборки</a>
            </div>

            <div class='admin-link'>
                <div class='admin-logo' style='background-image: url(../../../assets/comments.png);'></div>
                <%= link_to "Комментарии", comments_path %>
            </div>
    </div>
    <div class="admin-content">
        <form class='search-form'>
           <p><input type="search" name="q" placeholder="🔍 Введите название плейлиста"></p>
           <!-- <input type="submit" value="Найти"> -->
        </form>
        <div class='filter'>
            <span><%= link_to 'Все', admin_path() %></span>
            <% Category.all.each do |cat| %> |
            	<span><%= link_to cat.name, admin_path(category: cat.name) %></span>
            <% end %>
        </div>

        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Автор</th>
              <th>Название</th>
              <th>Жанр</th>
              <th>Активность</th>
              <th>Действия</th>
            </tr>
          </thead>

        <%#= link_to(image_tag(@post.image.thumb.url, alt: 'Image'), @post.image.url, target: '_blank') if @post.image? %>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <%#= link_to(image_tag(@post.image.thumb.url, alt: 'Image'), @post.image.url, target: '_blank') if @post.image? %>
                <td><%= post.id %></td>
                <td><%= link_to User.find(post.user_id).username, User.find(post.user_id) %></td>
                <td><%= link_to post.title, post %></td>
                <td><%= link_to post.category.name, post.category %></td>
                <td>
                    <%= post.likes.count %> <%= (post.likes.count) == 1 ? '👍' : '👍'%>
                    <%= post.comments.count %> <%= (post.comments.count) == 1 ? '💬' : '💬'%>
                </td>
                <td>
                    <span><%= link_to 'Изменить', edit_post_path(post) %></span>
                    <span class='delete'>
                        <%= link_to 'Удалить', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </span>

                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>


<%# link_to 'New Post', new_post_path %>



<% end %>