config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'admin', to: 'admin#index'

  controller :pages do
    get :qr_code_generator
    get :qr_code_download
  end

  resources :follows
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'about/index'
  get 'promo/index'
  resources :subscribers
  resources :posts do
    resources :comments
    resources :likes
    resources :favorites
  end

  resources :users
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  get 'users/:id/following', :to => "users#following", :as => :following

  get 'post/index'
  get 'welcome/index'
  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'

  resources :users, only: [:show, :edit, :update]


  get 'posts/:id', to: 'posts#show'

  get 'comments', to: 'comments#index'
  # get 'comments/:id', to: 'comments#show'


  root 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'promo#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
		mount_uploader :image, ImageUploader
		has_many :comments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		belongs_to :user
		belongs_to :category

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :likes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_posts, :through => :favorites, :source => :post

    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
    has_many :followees, through: :followed_users
    has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
    has_many :followers, through: :following_users
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all
  end

  # def index
  #   @users = User.all
  #   render component: 'Users', props: { users: @users }
  #   respond_to do |format|
  #     format.html  # index.html.erb
  #     format.json  { render :json => @users }
  #   end
  # end



  def edit
  end

  def update
    # current_user.update(params[:user])
    # redirect_to current_user
    respond_to do |format|
      if @user.update(user_params)
         format.html { redirect_to users_path, notice: 'The user info was successfully updated' }
         format.json { render :show, status: :ok, location: @user }

      else
         format.html { render :new, status: :unprocessable_entity }
         format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def show
    @user = User.find(params[:id])
    if @user
      @posts = @user.favorited_posts
      render actions: :show
      @favorites = @user.favorites.all
    else
        render file: 'public/404', status: 404, formats: [:html]
    end
  end

def favorited?(post)
    favorites.find_by(post_id: post.id).present?
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

  def follow
  @user = User.find(params[:id])
  current_user.followees << @user
  redirect_back(fallback_location: user_path(@user))
end

def unfollow
  @user = User.find(params[:id])
  current_user.followed_users.find_by(followee_id: @user.id).destroy
  redirect_back(fallback_location: user_path(@user))
end

def following
@user = User.find(params[:id])
if @user
  @follow = @user.followed_users
  render actions: :show
  @following = @user.followees.all
end
end


private

  def set_user
     @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :isadmin, :isblocked, :password)
  end


end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/edit.html.erb
<div class="stretch alone-form">
    <%= form_with model: @user, local: true, html: {class: "form-edit-user"} do |f| %>


    <h2>Пользователь</h2>

    <div class="field">
        <%= f.label :'Username' %>
          <%= f.text_field :username %>
    </div>

    <div class="field">
        <%= f.label :'Email' %>
          <%= f.text_field :email %>
    </div>


    <div class="field">
      <%= f.label :"Администратор" %>
      <%= f.check_box :isadmin %>
    </div>

    <div class="field">
        <%= f.label :'Заблокирован' %>
        <%= f.check_box :isblocked %>
    </div>

    <%= f.submit "Submit" %>



<% end %>




</div>

app/views/users/following.html.erb
<% @follow.each do |follow| %>
  <br><%= link_to follow.followee_id, user_path(follow.followee_id)  %>
<% end %>

app/views/users/index.html.erb
<% if user_signed_in? && current_user.isadmin == true%>


<div class="admin-page">
    <div class="admin-nav">
            <div class='admin-link' >
                <div class='admin-logo' style='background-image: url(../../../assets/posts.png);'></div>
                <strong><%= link_to "Публикации", admin_path %></strong>
            </div>
            <div class='admin-link' style='background: #C8DAE5;' >
                <div class='admin-logo' style='background-image: url(../../../assets/users.png);'></div>
                <%= link_to "Пользователи", users_path %>
            </div>
            <div class='admin-link'>
                <div class='admin-logo' style='background-image: url(../../../assets/genres.png);'></div>
                <%= link_to "Жанры", categories_path %>
            </div>
            <div class='admin-link' >
                <div class='admin-logo' style='background-image: url(../../../assets/collections.png);'></div>
                <a href="">Подборки</a>
            </div>

            <div class='admin-link'>
                <div class='admin-logo' style='background-image: url(../../../assets/comments.png);'></div>
                <%= link_to "Комментарии", comments_path %>
            </div>
    </div>
    <div class="admin-content">
        <form class='search-form'>
           <p><input type="search" name="q" placeholder="🔍 Введите ник пользователя"></p>
           <!-- <input type="submit" value="Найти"> -->
        </form>
        <table>
          <thead>
            <tr>
                <th>ID</th>
               <th>Пользователь</th>
              <th>Email</th>
              <th>Роль</th>
              <th>Блокировка</th>
              <th>Действия</th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= link_to user.username, user %></td>
                <td><%= user.email %></td>
                <td>
                    <% if user.isadmin == true%>
                        Администратор
                    <% else %>
                        -
                    <% end %>
                </td>
                <td>
                    <% if user.isblocked == true%>
                        <span style='color: #EE754A'>🞬</span>
                    <% else %>
                        -
                    <% end %>
                </td>
                <td>
                    <span><%= link_to 'Редактировать', edit_user_path(user) %></span>

                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="account-container">
  <% if @user.isblocked == false %>
  <div class="user-info">
    <%= react_component 'M_UserInfo', {
      user: @user,
      followees:  @user.followees.count,
      followers: @user.followers.count
    }%>

    <% if user_signed_in? && current_user.isadmin == true%>
        <div class="admin-btn">
            <%= link_to "Панель управления", admin_path %>
        </div>
    <% end %>

    <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>




  </div>
  <div class="user-posts">
    <% @posts.each do |post| %>
      <%= react_component 'M_Post', { title: post.title, post: post}%>
    <% end %>
    <div class='M_Post'>
      <a href="#">
      <%= react_component 'A_Cover', { tracks: "14"}%>
      </a>
      <div class='info'>
        <div class='datas'>
          <a href={`/posts/${this.props.post.id}`} class='title'>
            Плейлист для спорта
          </a>
          <span class='tracks'>
            14 треков
          </span>
        </div>
        <div class='tags'>
        <A_Tag tag={this.state.tags[0]} />
        <A_Tag tag={this.state.tags[1]} />
        </div>
      </div>
    </div>
  </div>
  <% else %>
  <p style='margin: 0 auto;'>Пользователь заблокирован</p>
  <% end %>
</div>