config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'admin', to: 'admin#index'

  controller :pages do
    get :qr_code_generator
    get :qr_code_download
  end

  resources :follows
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'about/index'
  get 'promo/index'
  resources :subscribers
  resources :posts do
    resources :comments
    resources :likes
    resources :favorites
  end

  resources :users
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  get 'users/:id/following', :to => "users#following", :as => :following

  get 'post/index'
  get 'welcome/index'
  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'

  resources :users, only: [:show, :edit, :update]


  get 'posts/:id', to: 'posts#show'

  get 'comments', to: 'comments#index'
  # get 'comments/:id', to: 'comments#show'


  root 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'promo#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
		mount_uploader :image, ImageUploader
		has_many :comments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		belongs_to :user
		belongs_to :category

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :likes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_posts, :through => :favorites, :source => :post

    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
    has_many :followees, through: :followed_users
    has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
    has_many :followers, through: :following_users
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description, :display_in_navbar)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>

    <h2>Категория</h2>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :'Название' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :'Описание' %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :'Отображение' %>
    <%= form.check_box :display_in_navbar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="stretch alone-form">


    <%= render 'form', category: @category %>

    <%= link_to 'Show', @category %> |
    <%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="admin-page">
    <div class="admin-nav">
            <div class='admin-link' >
                <div class='admin-logo' style='background-image: url(../../../assets/posts.png);'></div>
                <strong><%= link_to "Публикации", admin_path %></strong>
            </div>
            <div class='admin-link'>
                <div class='admin-logo' style='background-image: url(../../../assets/users.png);'></div>
                <%= link_to "Пользователи", users_path %>
            </div>
            <div class='admin-link' style='background: #C8DAE5;' >
                <div class='admin-logo' style='background-image: url(../../../assets/genres.png);'></div>
                <%= link_to "Жанры", categories_path %>
            </div>
            <div class='admin-link' >
                <div class='admin-logo' style='background-image: url(../../../assets/collections.png);'></div>
                <a href="">Подборки</a>
            </div>

            <div class='admin-link'>
                <div class='admin-logo' style='background-image: url(../../../assets/comments.png);'></div>
                <%= link_to "Комментарии", comments_path %>
            </div>
    </div>
    <div class="admin-content">
        <form class='search-form'>
           <p><input type="search" name="q" placeholder="🔍 Введите название жанра"></p>
        </form>
        <span class='create-new-btn'><%= link_to 'Добавить жанр', new_category_path %></span>
        <table>
          <thead>
            <tr>
              <th>Название</th>
              <th>Описание</th>
              <th>Отображение</th>
              <th>Действия</th>
            </tr>
          </thead>

          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td><%= category.description %></td>
                <td>
                    <% if category.display_in_navbar == true%>
                        ✓
                    <% else %>
                        ⨯
                    <% end %>
                </td>
                <td>
                    <span><%= link_to 'Изменить', edit_category_path(category) %></span>
                    <span class='delete'>
                        <%= link_to 'Удалить', category, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </span>

                </td>

              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

app/views/categories/new.html.erb
<div class="stretch alone-form">
    <%= render 'form', category: @category %>

    <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Display in navbar:</strong>
  <%= @category.display_in_navbar %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>